export const NODE_TYPES = Object.freeze({
  TEXT_MESSAGE: 'TEXT-MESSAGE-FLOW',
  ANSWER_BUTTON: 'ANSWER-BUTTON-FLOW',
  TEXT_EDITOR: 'TEXT-EDITOR-FLOW',
  DATA_TYPE_EXPECTED: 'DATA-TYPE-EXPECTED-FLOW',
  MESSAGE_WITH_OPTION: 'MESSAGE-WITH-OPTION-FLOW',
  FILE_UPLOAD: 'FILE-UPLOAD-FLOW',
})
